package cloudsync

import (
	"encoding/json"
	"testing"
)

// TestDecideNoteMatchesSharedFixture is the shared per-note decision test: the
// browser port (frontend/src/sync/decision.js) asserts against the SAME
// testdata/sync/decisions.json, so both runtimes must agree on every row of the
// fixed R1 decision table. The fixture pins the COMPLETE normalized decision —
// every field the coordinator executes on — including the deterministic
// conflict plan (identity, path, preserved markdown, state hashes, and the
// original-action fields), so a silent divergence on any executed field is
// caught. The fixture is regenerated by TestGenerateFixtures.
func TestDecideNoteMatchesSharedFixture(t *testing.T) {
	var fixture struct {
		Cases []struct {
			Name  string `json:"name"`
			Local struct {
				State       string `json:"state"`
				Path        string `json:"path"`
				Markdown    string `json:"markdown"`
				ContentHash string `json:"contentHash"`
				Revision    string `json:"revision"`
			} `json:"local"`
			Remote struct {
				State       string `json:"state"`
				Path        string `json:"path"`
				Markdown    string `json:"markdown"`
				ContentHash string `json:"contentHash"`
				Version     string `json:"version"`
				Retryable   bool   `json:"retryable"`
			} `json:"remote"`
			Baseline *struct {
				ContentHash   string `json:"contentHash"`
				Deleted       bool   `json:"deleted"`
				RemoteVersion string `json:"remoteVersion"`
			} `json:"baseline"`
			PathConflict bool `json:"pathConflict"`
			Expected     struct {
				SyncID        string `json:"syncId"`
				Kind          string `json:"kind"`
				Reason        string `json:"reason"`
				ContentHash   string `json:"contentHash"`
				Deleted       bool   `json:"deleted"`
				Path          string `json:"path"`
				Markdown      string `json:"markdown"`
				Version       string `json:"version"`
				LocalRevision string `json:"localRevision"`
				Conflict      *struct {
					SourceSyncID      string `json:"sourceSyncId"`
					ConflictSyncID    string `json:"conflictSyncId"`
					ConflictPath      string `json:"conflictPath"`
					ConflictMarkdown  string `json:"conflictMarkdown"`
					LocalStateHash    string `json:"localStateHash"`
					RemoteStateHash   string `json:"remoteStateHash"`
					OriginalTombstone bool   `json:"originalTombstone"`
					OriginalVersion   string `json:"originalVersion"`
				} `json:"conflict"`
			} `json:"expected"`
		} `json:"cases"`
	}
	if err := json.Unmarshal(loadFixture(t, "decisions.json"), &fixture); err != nil {
		t.Fatal(err)
	}
	if len(fixture.Cases) == 0 {
		t.Fatal("decisions.json has no cases")
	}
	for _, tc := range fixture.Cases {
		loc := NoteLocalObservation{
			SyncID:      testNoteSyncID,
			State:       localStateFromFixtureString(tc.Local.State),
			Path:        tc.Local.Path,
			Markdown:    tc.Local.Markdown,
			ContentHash: tc.Local.ContentHash,
			Revision:    tc.Local.Revision,
		}
		rem := NoteRemoteObservation{
			SyncID:      testNoteSyncID,
			State:       remoteStateFromFixtureString(tc.Remote.State),
			Path:        tc.Remote.Path,
			Markdown:    tc.Remote.Markdown,
			ContentHash: tc.Remote.ContentHash,
			Version:     tc.Remote.Version,
			Retryable:   tc.Remote.Retryable,
		}
		var b *Baseline
		if tc.Baseline != nil {
			b = &Baseline{
				ContentHash:   tc.Baseline.ContentHash,
				Deleted:       tc.Baseline.Deleted,
				RemoteVersion: tc.Baseline.RemoteVersion,
			}
		}
		d := DecideNote(loc, rem, b, tc.PathConflict)
		exp := tc.Expected
		if d.SyncID != exp.SyncID {
			t.Errorf("%s: syncId = %q, want %q", tc.Name, d.SyncID, exp.SyncID)
		}
		if got := d.Kind.String(); got != exp.Kind {
			t.Errorf("%s: kind = %s (%s), want %s", tc.Name, got, d.Reason, exp.Kind)
		}
		if d.Reason != exp.Reason {
			t.Errorf("%s: reason = %q, want %q", tc.Name, d.Reason, exp.Reason)
		}
		if d.ContentHash != exp.ContentHash {
			t.Errorf("%s: contentHash = %q, want %q", tc.Name, d.ContentHash, exp.ContentHash)
		}
		if d.Deleted != exp.Deleted {
			t.Errorf("%s: deleted = %v, want %v", tc.Name, d.Deleted, exp.Deleted)
		}
		if d.Path != exp.Path {
			t.Errorf("%s: path = %q, want %q", tc.Name, d.Path, exp.Path)
		}
		if d.Markdown != exp.Markdown {
			t.Errorf("%s: markdown = %q, want %q", tc.Name, d.Markdown, exp.Markdown)
		}
		if d.Version != exp.Version {
			t.Errorf("%s: version = %q, want %q", tc.Name, d.Version, exp.Version)
		}
		if d.LocalRevision != exp.LocalRevision {
			t.Errorf("%s: localRevision = %q, want %q", tc.Name, d.LocalRevision, exp.LocalRevision)
		}
		if c := d.Conflict; c != nil {
			if exp.Conflict == nil {
				t.Errorf("%s: unexpected conflict plan %+v", tc.Name, c)
				continue
			}
			if c.SourceSyncID != exp.Conflict.SourceSyncID {
				t.Errorf("%s: conflict.sourceSyncId = %q, want %q", tc.Name, c.SourceSyncID, exp.Conflict.SourceSyncID)
			}
			if c.ConflictSyncID != exp.Conflict.ConflictSyncID {
				t.Errorf("%s: conflict.conflictSyncId = %q, want %q", tc.Name, c.ConflictSyncID, exp.Conflict.ConflictSyncID)
			}
			if c.ConflictPath != exp.Conflict.ConflictPath {
				t.Errorf("%s: conflict.conflictPath = %q, want %q", tc.Name, c.ConflictPath, exp.Conflict.ConflictPath)
			}
			if c.ConflictMarkdown != exp.Conflict.ConflictMarkdown {
				t.Errorf("%s: conflict.conflictMarkdown = %q, want %q", tc.Name, c.ConflictMarkdown, exp.Conflict.ConflictMarkdown)
			}
			if c.LocalStateHash != exp.Conflict.LocalStateHash {
				t.Errorf("%s: conflict.localStateHash = %q, want %q", tc.Name, c.LocalStateHash, exp.Conflict.LocalStateHash)
			}
			if c.RemoteStateHash != exp.Conflict.RemoteStateHash {
				t.Errorf("%s: conflict.remoteStateHash = %q, want %q", tc.Name, c.RemoteStateHash, exp.Conflict.RemoteStateHash)
			}
			if c.OriginalTombstone != exp.Conflict.OriginalTombstone {
				t.Errorf("%s: conflict.originalTombstone = %v, want %v", tc.Name, c.OriginalTombstone, exp.Conflict.OriginalTombstone)
			}
			if c.OriginalVersion != exp.Conflict.OriginalVersion {
				t.Errorf("%s: conflict.originalVersion = %q, want %q", tc.Name, c.OriginalVersion, exp.Conflict.OriginalVersion)
			}
		} else if exp.Conflict != nil {
			t.Errorf("%s: missing conflict plan", tc.Name)
		}
	}
}

func localStateFromFixtureString(s string) LocalState {
	switch s {
	case "live":
		return LocalLive
	case "absent":
		return LocalAbsent
	default:
		return LocalUnknown
	}
}

func remoteStateFromFixtureString(s string) RemoteState {
	switch s {
	case "live":
		return RemoteLive
	case "tombstone":
		return RemoteTombstone
	case "missing":
		return RemoteMissing
	default:
		return RemoteInvalid
	}
}
