// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ChangeDataDir() {
  return window['go']['main']['App']['ChangeDataDir']();
}

export function GetDataDir() {
  return window['go']['main']['App']['GetDataDir']();
}
